### ISSUE TITLE
Commands should be displayed like this (instead on typing --- person should click nd select)

### ISSUE THREAD

**Issue by SukhmanpreetSingh** [KhalisFoundation/sttm-telegram-bot#5]
![img_20180709_141046](https://user-images.githubusercontent.com/33250386/42440085-3780e6e4-8382-11e8-9c58-f117117bcac1.JPG)

**Comment by bogas04** [comment]
Added the commands. 
![screenshot_20180711-004010](https://user-images.githubusercontent.com/6177621/42531989-15efefbc-84a3-11e8-84f7-97a25f480438.jpg)
